### ISSUE TITLE
Logistics

### ISSUE THREAD

**Issue by karthik** [karthik/2014-02-13-UNSW#3]
### For the host

@enterthesloth
- [ ] Make sure the room has enough outlets for everyone to use. 
- [ ] Make sure the room has wifi (or set in motion whatever we need to do to make that happen)
- [x] Set up eventbrite (possibly with a private code) and set limit to total spots - reserved spots.
  (note, it looks like eventbrite registration can easily be included into the gh-pages template we have. Should I find out more from Amy Brown?)
### For instructors (to do 7-10 days before bootcamp)
- [ ] Once all 40 (or total limit) is reached, send out installation instructions 1 wk before (any earlier is too soon).
- [ ] Mostly make sure students have RStudio, latest R, and running `has_devel()` returns `TRUE` (means devtools, RTools, and Linux equivalent are properly installed). There are some Mavericks specific instructions we need to include
- [ ] Set up survey to find out what the target audience is most keen on learning + past experience w/ various tools. See old example [here](https://docs.google.com/forms/d/12MyEsQMzZsv5Ghkt-VD276eD5zfIPxegPFi2jesmfOo/edit).

For @dfalster and @richfitz 
- [x] Find two helpers. Preferably women coders in the Sydney area.

**Comment by andrewletten** [comment]
Hey Karthik, thanks for putting this together. Yep, it would be nice if we can include the eventbrite registration on the bootcamp website...I need to get in touch with Amy to setup eventbrite so will check if it's possible.

Cheers
Andrew

**Comment by karthik** [comment]
How about something like this? [Tito.io](https://tito.io/karthik/swc-uts-feb-2014) is a new service but does the same in an elegant way.

**Comment by karthik** [comment]
I forgot to add. One can set number of spots (currently set to 30), with 10 more that will open up later. Those ten will require a code that we set. You can email a direct link to those spots with the code at the same time as the regular tickets.

**Comment by andrewletten** [comment]
The tito page looks good...they charge 3% per ticket for the base plan which seems pretty reasonable. Was that a test page you made or can we add addidttional content onto it? Otherwise i'll just go ahead and make a new one for UNSW. Also, def makes more sense to reserve the sign-up code for external folk.

**Comment by karthik** [comment]
That was just a test page that I made. Since you are actually collecting money, you should just set up your own account and create an event. They have an option to embed a registration form into a web page through a widget but that doesn't appear to work on GitHub pages. So we could just throw a link at the bottom that says: "Register Now" and have that direct people to the tito registration page.

How does that sound to you?

**Comment by andrewletten** [comment]
Apologies for delay reply, but now turns out we might have to also run the UNSW registration through an internal system. I have a meeting with our centre manager today to sort it out so hopefully will get something up by the end of the week. The internal system isn't as slick as tito (may have to have two differnt links for internals and externals) but does mean we won't sacrifice a percentage to both tito and the payment provider (e.g. paypal)...will keep you posted.

**Comment by karthik** [comment]
No worries Andrew. As I suggested to Aaron, let's do both. Tito will allow us to get everyone to commit quickly. Once we've filled all slots, we can get everyone to complete the university formality before they attend.

**Comment by andrewletten** [comment]
Yep, that makes a lot of sense, especialy as I don't know how long it will take to get the internal system up. Will get on it asap.

**Comment by andrewletten** [comment]
Hi All, here is a [preview](https://tito.io/swc/unsw2014) of the registration page for the UNSW bootcamp (note that internals and externals registrations will use two different links with 30 and 10 spot limits respectively). Please let me know if you have any edits, particularly with respect to the content and your bios as I just copied them from the software carpentry website (Karthik and Dan) and your website Rich (maybe some additional stuff about NiceR code and your R package(s)?).

I also took the liberty of linking to Day 1 of the NiceR code 'Introduction to R' module as a guideline on expected knowledge - hope you guys are alright with that?!

**Comment by andrewletten** [comment]
If it helps, i've temporarily added the registration page content to the README.md so you can edit directly...

**Comment by karthik** [comment]
Discussion on helpers has moved to #5

**Comment by dfalster** [comment]
Closing as this has well & truly expired!
