### ISSUE TITLE
Find helpers for bootcamp, ideally women

### ISSUE THREAD

**Issue by dfalster** [karthik/2014-02-13-UNSW#5]
Have the following candidates:
- Natalia Vaudagnotto: honours student in [Tanaka lab at UNSW](http://www.emi.unsw.edu.au/~tanakalab/people.html) works in bioinformatics, originally from computer science.
- Carmen Chan: Phd student in [Tanaka lab at UNSW](http://www.emi.unsw.edu.au/~tanakalab/people.html) experience with R and shell
- Jennifer Buhler: PhD student in Computer Science at UNSW, otherwise works at Intersect.
- Diego Barneche: PHD student at Macquarie University. Can teach or tutor.

Carmen and Natalia definite, Jennifer keen but cannot commit until closer to day, once she knows how her PhD is tracking and whether she can spare the time.

I suggest we say yes to the three women and get Diego involved with the UTS camp.

**Comment by karthik** [comment]
Sounds great. Do we have enough helpers or maybe use more? My Twitter search led me to [this person](https://twitter.com/cheshireb/status/409234384869281794). Happy to get in touch if needed.

**Comment by dfalster** [comment]
Yes do, great if she can come to UTS bootcamp as we could use another
female tutor there. Is 4 tutors plus 3 instructors excessive? Rich thinks
more the better.

**Comment by andrewletten** [comment]
If we do end up needing another person at UNSW (in addition to the female tutors) and are happy for them to be male, then it would be great if we can hold that spot for Ned Haughton. Ned put his hand up at the beginning of the year to help (after attending a bootcamp run by Greg in Melbourne) and is on top of git, R, knitr and much more. He also has experience teaching git to naive ecologists (including myself)...

**Comment by karthik** [comment]
@dfalster She said yes and is ok to attend either one. So I will tell her to help with the one at UTS.

**Comment by dfalster** [comment]
Have emailed Natalia, Carmen, Jennifer to say yes, please help.

**Comment by dfalster** [comment]
Will Cornwell is our final helper for UNSW bootcamp. Will is a new academic within the biology department at UNSW with experience in R, git, github. will be great to have at least one local academic involved, to build some local expertise and have someone in the department students can contact after the event.

**Comment by dfalster** [comment]
So we have
- Natalia Vaudagnotto: honours student in [Tanaka lab at UNSW](http://www.emi.unsw.edu.au/~tanakalab/people.html) works in bioinformatics, originally from computer science.
- Carmen Chan: Phd student in [Tanaka lab at UNSW](http://www.emi.unsw.edu.au/~tanakalab/people.html) experience with R and shell
- Jennifer Buhler: PhD student in Computer Science at UNSW, otherwise works at Intersect. (Will confirm closer to the day)
- Will Cornwell: Academic at UNSW in biology

**Comment by karthik** [comment]
Fantastic! Thanks Daniel.
